/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddCustomTag: typeof import('./src/components/HistoryDetail/components/AddCustomTag/index.vue')['default']
    BottomNavigation: typeof import('./src/components/BottomNavigation/index.vue')['default']
    CollapsiblePanel: typeof import('./src/components/CollapsiblePanel/index.vue')['default']
    DetailInfo: typeof import('./src/components/HistoryDetail/components/DetailInfo/index.vue')['default']
    HistoryDetail: typeof import('./src/components/HistoryDetail/index.vue')['default']
    ImageContrast: typeof import('./src/components/ImageContrast/index.vue')['default']
    ImageStageActionButtons: typeof import('./src/components/ImageStageActionButtons/index.vue')['default']
    Layouts: typeof import('./src/components/Layouts/index.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    NavBar: typeof import('./src/components/NavBar/index.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutImagePreview: typeof import('@nutui/nutui-taro')['ImagePreview']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    PublishWork: typeof import('./src/components/HistoryDetail/components/PublishWork/index.vue')['default']
    RootPortalEl: typeof import('./src/components/RootPortalEl/index.vue')['default']
    UserAndWorkInfo: typeof import('./src/components/HistoryDetail/components/UserAndWorkInfo/index.vue')['default']
  }
}
